# AWS EKS integration using IAM Roles for Service Accounts (IRSA)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secure-api-sa
  namespace: secure-api-ns
  annotations:
    # Replace '123456789012' with your real AWS Account ID
    # and 'secure-api-execution-role' with your AWS IAM Role name
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/secure-api-execution-role
  labels:
    app.kubernetes.io/name: secure-api
    app.kubernetes.io/part-of: spring-rbac-showcase
# DevSecOps Best Practice: Let the EKS Webhook manage the mounting of the project volume token.
# When IRSA is annotated, the webhook will automatically handle mounting the temporary STS token.
automountServiceAccountToken: true
