# Dedicated ServiceAccount for the Spring Boot application to avoid using 'default'
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secure-api-sa
  namespace: secure-api-ns
  labels:
    app.kubernetes.io/name: secure-api
    app.kubernetes.io/part-of: spring-rbac-showcase
# DevSecOps Best Practice: Do not automatically mount the API credentials token.
# This prevents an attacker from accessing the K8s API if the container is compromised.
automountServiceAccountToken: false
